-- UrbanFood schema for Supabase Postgres
-- Compatible with current backend models/routes

BEGIN;

-- =========================
-- Generic updated_at trigger
-- =========================
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS trigger AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- =========================
-- Table: usuarios
-- =========================
CREATE TABLE IF NOT EXISTS public.usuarios (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(80) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  rol VARCHAR(30) NOT NULL,
  nombre VARCHAR(120),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT usuarios_rol_check CHECK (rol IN ('admin', 'vendedor'))
);

DROP TRIGGER IF EXISTS trg_usuarios_updated_at ON public.usuarios;
CREATE TRIGGER trg_usuarios_updated_at
BEFORE UPDATE ON public.usuarios
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

-- =========================
-- Table: productos
-- =========================
CREATE TABLE IF NOT EXISTS public.productos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo VARCHAR(30) NOT NULL UNIQUE,
  nombre VARCHAR(120) NOT NULL,
  precio INTEGER NOT NULL,
  categoria VARCHAR(40),
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT productos_precio_check CHECK (precio >= 0),
  CONSTRAINT productos_categoria_check CHECK (categoria IN ('hamburguesa', 'perro', 'bebida', 'adicional'))
);

DROP TRIGGER IF EXISTS trg_productos_updated_at ON public.productos;
CREATE TRIGGER trg_productos_updated_at
BEFORE UPDATE ON public.productos
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

-- =========================
-- Table: ventas
-- NOTE: current backend stores one row per item sold.
-- =========================
CREATE TABLE IF NOT EXISTS public.ventas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fecha TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  producto_id BIGINT NOT NULL,
  cantidad INTEGER NOT NULL,
  precio_unitario INTEGER NOT NULL,
  total INTEGER NOT NULL,
  vendedor_id BIGINT NOT NULL,
  estado VARCHAR(40) NOT NULL DEFAULT 'pendiente',
  pago VARCHAR(40) NOT NULL DEFAULT 'efectivo',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT ventas_cantidad_check CHECK (cantidad > 0),
  CONSTRAINT ventas_precio_unitario_check CHECK (precio_unitario >= 0),
  CONSTRAINT ventas_total_check CHECK (total >= 0),
  CONSTRAINT ventas_estado_check CHECK (estado IN ('pendiente', 'pagado', 'cancelado')),
  CONSTRAINT ventas_pago_check CHECK (pago IN ('efectivo', 'transferencia', 'tarjeta')),
  CONSTRAINT ventas_producto_fk FOREIGN KEY (producto_id) REFERENCES public.productos(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT ventas_vendedor_fk FOREIGN KEY (vendedor_id) REFERENCES public.usuarios(id) ON UPDATE CASCADE ON DELETE RESTRICT
);

-- =========================
-- Indexes for performance
-- =========================
CREATE INDEX IF NOT EXISTS idx_ventas_fecha ON public.ventas (fecha DESC);
CREATE INDEX IF NOT EXISTS idx_ventas_vendedor ON public.ventas (vendedor_id);
CREATE INDEX IF NOT EXISTS idx_ventas_producto ON public.ventas (producto_id);
CREATE INDEX IF NOT EXISTS idx_ventas_estado ON public.ventas (estado);
CREATE INDEX IF NOT EXISTS idx_productos_categoria ON public.productos (categoria);

-- =========================
-- Initial seed (safe UPSERTs)
-- Passwords are plain text for first login compatibility.
-- Then update from backend using hashed passwords.
-- =========================
INSERT INTO public.usuarios (username, password, rol, nombre)
VALUES
  ('admin', 'admin123', 'admin', 'Administrador'),
  ('vendedor1', 'vende123', 'vendedor', 'Vendedor 1'),
  ('vendedor2', 'vende456', 'vendedor', 'Vendedor 2')
ON CONFLICT (username) DO NOTHING;

INSERT INTO public.productos (codigo, nombre, precio, categoria)
VALUES
  ('MINIH', 'Mini H', 5500, 'hamburguesa'),
  ('HSINT', 'H Sin T', 10000, 'hamburguesa'),
  ('HCONT', 'H Cont', 11000, 'hamburguesa'),
  ('HDOBLE', 'H Doble', 18000, 'hamburguesa'),
  ('PSINT', 'P Sin T', 8000, 'perro'),
  ('PCONT', 'P Cont', 9000, 'perro'),
  ('COCA', 'Coca-Cola', 3000, 'bebida'),
  ('CUATRO', 'Cuatro', 3000, 'bebida'),
  ('JUGOS', 'Jugos', 2000, 'bebida'),
  ('TE', 'Té', 2000, 'bebida'),
  ('AGUA', 'Agua', 2000, 'bebida'),
  ('AQUESO', 'A Queso', 1000, 'adicional'),
  ('ATOCINO', 'A Tocino', 1000, 'adicional')
ON CONFLICT (codigo) DO NOTHING;

COMMIT;
